###  localhost requests
@localhostName = http://localhost:8080

### returns a json object with all contacts data.
GET {{localhostName}}/contacts

### returns a json object with a specific contact.
GET {{localhostName}}/contacts/650c5812c06bc031e32200a1

### creates a new contact.
POST {{localhostName}}/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Americo",
    "lastName":"Kutomi",
    "email":"americo@test.com",
    "favoriteColor":"yellow",
    "birthday":"05/31/1999"
}

### updates an existing contact.
PUT {{localhostName}}/contacts/650c5812c06bc031e32200a1 HTTP/1.1
content-type: application/json

{
  "firstName":"Bill",
  "lastName":"Gates",
  "email":"billgates@test.com",
  "favoriteColor":"Blue",
  "birthday":"12/22/1950"
}

### removes an existing contact
DELETE {{localhostName}}/contacts/66742e379ca21b5d1b9668d9 HTTP/1.1

### opens the API documentation 
GET {{localhostName}}/api-docs

###  Render requests

@publishedHostName = https://cse-341-contacts-i6dr.onrender.com

### returns a json object with all contacts data.
GET {{publishedHostName}}/contacts

### returns a json object with a specific contact.
GET {{publishedHostName}}/contacts/650c5812c06bc031e32200a1

### creates a new contact.
POST {{publishedHostName}}/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Americo",
    "lastName":"Kutomi",
    "email":"americo@test.com",
    "favoriteColor":"yellow",
    "birthday":"05/31/1999"
}

### updates an existing contact.
PUT {{publishedHostName}}/contacts/650c5812c06bc031e32200a1 HTTP/1.1
content-type: application/json

{
  "firstName":"Bill",
  "lastName":"Gates",
  "email":"billgates@test.com",
  "favoriteColor":"Blue",
  "birthday":"12/22/1950"
}

### removes an existing contact
DELETE {{publishedHostName}}/contacts/66742e379ca21b5d1b9668d9 HTTP/1.1

### opens the API documentation 
GET {{publishedHostName}}/api-docs
