// localhost
@hostname = http://localhost:8080

### returns a json object with all contacts data.
GET {{hostname}}/contacts

### returns a json object with a specific contact.
GET {{hostname}}/contacts/650c5812c06bc031e32200a1

### creates a new contact.
POST {{hostname}}/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Americo",
    "lastName":"Kutomi",
    "email":"americo@test.com",
    "favoriteColor":"yellow",
    "birthday":"05/31/1999"
}

### updates an existing contact.
PUT {{hostname}}/contacts/650c5812c06bc031e32200a1 HTTP/1.1
content-type: application/json

{
  "firstName":"Bill",
  "lastName":"Gates",
  "email":"billgates@test.com",
  "favoriteColor":"Blue",
  "birthday":"12/22/1950"
}

### removes an existing contact
DELETE {{hostname}}/contacts/66742e379ca21b5d1b9668d9 HTTP/1.1

###

// Render
GET https://cse-341-contacts-i6dr.onrender.com/contacts
# the request above returns a json object with all contacts data.

GET https://cse-341-contacts-i6dr.onrender.com/contacts/650c5812c06bc031e32200a1
# the request above returns a json object with a specific contact.
