GET http://localhost:8080/contacts
# local: the request above returns a json object with all contacts data.

GET http://localhost:8080/contacts/650c5812c06bc031e32200a1
# local: the request above returns a json object with a specific contact.

GET https://cse-341-contacts-i6dr.onrender.com/contacts
# Render: the request above returns a json object with all contacts data.

GET https://cse-341-contacts-i6dr.onrender.com/contacts/650c5812c06bc031e32200a1
# Render: the request above returns a json object with a specific contact.
